[package]
name = "wikiquotes-structured"
description = "Turn a Wikiquote XML dump into structured quotes"
version = "0.1.0"
edition = "2024"
keywords = ["wikiquotes", "parsing", "wikitext"]
categories = ["structured-data", "wikiquotes"]
repository = "https://github.com/santhoshtr/wikiquotes-structured"
license = "MIT"

[dependencies]
anyhow = "1.0.104"
arrow = "59.3.0"
blake3 = "1.8.7"
clap = { version = "4.6.6", features = ["derive"] }
flate2 = "1.1.10"
parquet = "59.3.0"
quick-xml = { version = "0.42.0", features = ["escape-html"] }
rayon = "1.12.0"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_arrow = { version = "0.15.0", features = ["arrow-59"] }
serde_json = "1.0.151"
tree-sitter = "0.27.0"
tree-sitter-wikitext = "0.1.3"
